[service.backend]
# Tell Railpack to use Python 3.11
runtime = "python@3.11"

# Set working directory to your backend folder
root = "backend"

# Install dependencies
build = "pip install -r requirements.txt"

# Run your app with Gunicorn
start = "gunicorn app:app --bind 0.0.0.0:$PORT"
